name: CI

permissions:
  contents: write

on:
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Update package.json version
      run: |
        PACKAGE_VERSION=$(git describe --tags --abbrev=0)
        echo "Setting package.json version to $PACKAGE_VERSION"
        jq '.version = "'"$PACKAGE_VERSION"'"' package.json > package_temp.json
        mv package_temp.json package.json
    - name: Build it
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install
        npm ci
        npm run dist
    - uses: actions/upload-artifact@v3
      with:
        name: linux-binaries
        path: |
          dist/xwiki-browser-amd64.deb
          dist/xwiki-browser-x86_64.AppImage
          dist/xwiki-browser-arm64.deb
          dist/xwiki-browser-arm64.AppImage
          dist/latest-linux.yml
          dist/latest-linux-arm64.yml
  build-mac:
    name: macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Update package.json version
      run: |
        PACKAGE_VERSION=$(git describe --tags --abbrev=0)
        echo "Setting package.json version to $PACKAGE_VERSION"
        jq '.version = "'"$PACKAGE_VERSION"'"' package.json > package_temp.json
        mv package_temp.json package.json
    - name: Build it
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install
        npm ci
        npm run lint
        npm run dist
    - uses: actions/upload-artifact@v3
      with:
        name: mac-binaries
        path: |
          dist/xwiki-browser.dmg
          dist/xwiki-browser.zip
          dist/latest-mac.yml
  build-windows:
    name: Windows
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Update package.json version
      run: |
        PACKAGE_VERSION=$(git describe --tags --abbrev=0)
        echo "Setting package.json version to $PACKAGE_VERSION"
        jq '.version = "'"$PACKAGE_VERSION"'"' package.json > package_temp.json
        mv package_temp.json package.json
    - name: Build it
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install
        npm ci
        npm run dist
    - uses: actions/upload-artifact@v3
      with:
        name: windows-binaries
        path: |
          dist/xwiki-browser.exe
          dist/latest.yml
