name: CI

permissions:
  contents: write

on:
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Get branch name
      id: get_branch
      run: echo "BRANCH_NAME=$(git branch --show-current)" >> $GITHUB_ENV
    - name: Update package.json version
      run: |
        echo "Setting package.json version to $BRANCH_NAME"
        jq '.version = "'"$BRANCH_NAME"'"' package.json > package_temp.json
        mv package_temp.json package.json
    - name: Build it
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install
        npm ci
        npm run dist
    - uses: actions/upload-artifact@v3
      with:
        name: linux-binaries
        path: |
          dist/xwiki-browser-amd64.deb
          dist/xwiki-browser-x86_64.AppImage
          dist/xwiki-browser-arm64.deb
          dist/xwiki-browser-arm64.AppImage
          dist/latest-linux.yml
          dist/latest-linux-arm64.yml
  build-mac:
    name: macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Get branch name
      id: get_branch
      run: echo "BRANCH_NAME=$(git branch --show-current)" >> $GITHUB_ENV
    - name: Update package.json version
      run: |
        echo "Setting package.json version to $BRANCH_NAME"
        jq '.version = "'"$BRANCH_NAME"'"' package.json > package_temp.json
        mv package_temp.json package.json
    - name: Build it
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install
        npm ci
        npm run lint
        npm run dist
    - uses: actions/upload-artifact@v3
      with:
        name: mac-binaries
        path: |
          dist/xwiki-browser.dmg
          dist/xwiki-browser.zip
          dist/latest-mac.yml
  build-windows:
    name: Windows
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Update package.json version
      run: |
        $BRANCH_NAME = "${{ github.head_ref }}"
        echo "Setting package.json version to $BRANCH_NAME"
        jq ('version = "' + $BRANCH_NAME + '"') package.json > package_temp.json
        Move-Item -Path package_temp.json -Destination package.json -Force
      shell: pwsh
    - name: Build it
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install
        npm ci
        npm run dist
    - uses: actions/upload-artifact@v3
      with:
        name: windows-binaries
        path: |
          dist/xwiki-browser.exe
          dist/latest.yml
