name: PRE-RELEASE

permissions:
  contents: write
  
on: workflow_dispatch

jobs:
  build-and-release:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-2022
          - macos-latest
        node:
          - 18

    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}

    env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: nyaa8/package-version@v1.0.3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - if: matrix.os == 'macos-latest' 
        run: npm run lint
      - run: npm run dist
      - uses: actions/upload-artifact@v3
        with:
          name: xwiki-browser-${{ matrix.os }}-binaries
          path: |
            dist/xwiki-browser-amd64.deb
            dist/xwiki-browser-x86_64.AppImage
            dist/xwiki-browser-arm64.deb
            dist/xwiki-browser-arm64.AppImage
            dist/latest-linux.yml
            dist/latest-linux-arm64.yml
            dist/xwiki-browser.dmg
            dist/xwiki-browser.zip
            dist/latest-mac.yml
            dist/xwiki-browser.exe
            dist/latest.yml
      - uses: "softprops/action-gh-release@v0.1.15"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: 'v${{ env.PACKAGE_VERSION }}'
          generate_release_notes: true
          fail_on_unmatched_files: false
          prerelease: true
          files: |
            dist/xwiki-browser-amd64.deb
            dist/xwiki-browser-x86_64.AppImage
            dist/xwiki-browser-arm64.deb
            dist/xwiki-browser-arm64.AppImage
            dist/latest-linux.yml
            dist/latest-linux-arm64.yml
            dist/xwiki-browser.dmg
            dist/xwiki-browser.zip
            dist/latest-mac.yml
            dist/xwiki-browser.exe
            dist/latest.yml
